[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
    "-C", "link-arg=-fuse-ld=mold",
    "-C", "symbol-mangling-version=v0",
]

[registries]
bearcove = { index = "https://code.bearcove.cloud/bearcove/_cargo-index.git" }
